# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

---
- name: GCloud login
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/gcp.yaml
  roles:
    # this is needed for the gcp-ssh-wrapper.sh script
    - gcp-login

- name: Prepare Gitpod GCP resources
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/gcp.yaml
    - vars/gcp-dns.yaml
  roles:
    - gcp

- name: Prepare GitLab GCP resources
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/gcp.yaml
    - vars/gcp-dns.yaml
    - vars/gitlab.yaml
  vars:
    instance_name: "{{ gitlab_instance_name }}"
    domain: "{{ gitlab_domain }}"
  roles:
    - gcp-instance

- name: Prepare Registry GCP resources
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/gcp.yaml
    - vars/gcp-dns.yaml
    - vars/registry.yaml
  vars:
    instance_name: "{{ registry_instance_name }}"
    domain: "{{ registry_domain }}"
  roles:
    - gcp-instance

- name: Refresh inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - meta: refresh_inventory

- name: Wait for connection
  hosts: all
  gather_facts: no
  tasks:
    - wait_for_connection:

- name: Restore from GCP bucket
  hosts:
    - gitpod_node_main
    - instance_gitlab
    - instance_registry
  vars_files:
    - vars/common-airgap.yaml
    - vars/gcp.yaml
    - vars/gitlab.yaml
    - vars/registry.yaml
  roles:
    - gcp-bucket-restore

- name: Install GitLab
  hosts: instance_gitlab
  vars_files:
    - vars/gitlab.yaml
  roles:
    - install-gitlab

- name: Install Registry
  hosts: instance_registry
  var_files:
    - vars/registry.yaml
  roles:
    - install-docker
    - install-registry

- name: Prepare DNS
  hosts: gitpod_node_main
  vars_files:
    - vars/common-airgap.yaml
    - vars/gcp.yaml
    - vars/gcp-dns.yaml
  roles:
    - gcp-dns

- name: Prepare Gitpod installer
  hosts: gitpod_node_main
  roles:
    - gitpod-installer

- name: Mirror Gitpod images
  hosts:
    - gitpod_node_main
    - gitpod_node_worker
  roles:
    - install-docker
    - mirror-gitpod-images

- name: Generate cluster secret
  hosts: localhost
  gather_facts: no
  tasks:
    - set_fact:
        k3s_cluster_secret: "{{ lookup('community.general.random_string', length=40) }}"

- name: Install k3s
  hosts:
    - gitpod_node_main
    - gitpod_node_worker
  vars_files:
    - vars/common-airgap.yaml
  vars:
    airgap: true
  roles:
    - install-k3s

- name: Install Gitpod
  hosts:
    - gitpod_node_main
  vars_files:
    - vars/common-airgap.yaml
  vars:
    airgap: true
  roles:
    - install-gitpod-k3s

- name: Disconnect Gitpod nodes from the internet and install Gitpod
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/common-airgap.yaml
    - vars/gcp.yaml
  roles:
    - gcp-airgap

- name: Install WireGuard on bastion host
  hosts: instance_bastion
  roles:
    - install-wireguard
