# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

---
- name: GCloud login
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/gcp.yaml
  roles:
    # this is needed for the gcp-ssh-wrapper.sh script
    - gcp-login

- name: Prepare GitLab GCP resources
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/gcp.yaml
    - vars/gcp-dns.yaml
    - vars/gitlab.yaml
  vars:
    instance_name: "{{ gitlab_instance_name }}"
    domain: "{{ gitlab_domain }}"
  roles:
    - gcp-instance

- name: Refresh inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - meta: refresh_inventory

- name: Wait for connection
  hosts: all
  gather_facts: no
  tasks:
    - wait_for_connection:

- name: Restore from GCP bucket
  hosts: instance_gitlab
  vars_files:
    - vars/common.yaml
    - vars/gcp.yaml
    - vars/gitlab.yaml
  roles:
    - gcp-bucket-restore

- name: Install GitLab
  hosts: instance_gitlab
  vars_files:
    - vars/gitlab.yaml
  roles:
    - install-gitlab
