# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

---
gitlab_instance_name: gitlab
gitlab_domain: gitlab-1.testing.gitpod-self-hosted.com
