name: Code Nightly

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Code Nightly"]
    types: [completed]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Auth Google Cloud SDK
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - run: |
          sleep 90s
          gcloud auth configure-docker --quiet

          # this is because we don't want to increate gitpod-build-main number, we can choose a name
          cp .werft/build.yaml .werft/test.yaml
          # version is actual namespace that werft is build, --job-file should be same with above
          werft run github -a version=staging-test-1 --job-file .werft/test.yaml github.com/gitpod-io/gitpod:main
          # run test
          werft run github -j .werft/run-integration-tests.yaml -a testPattern=ide.test -a namespace=staging-test-1 -a version=gitpod-test-main.1 -f
          # final we remove the temp preview environment
          werft run github -a namespace=staging-test-1 --remote-job-path .werft/wipe-devstaging.yaml github.com/gitpod-io/gitpod:main

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.IDE_SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
