name: JetBrains Test
on:
  workflow_dispatch:
    inputs:
      secret_gateway_link:
        type: string
        description: GatewayLink
        required: true
      secret_owner_token:
        type: string
        description: OwnerToken
        required: true
jobs:
  jetbrains-smoke-test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Gateway Plugin
        working-directory: ./components/ide/jetbrains/gateway-plugin
        run: |
          ./gradlew -PpluginVersion=test buildPlugin
      - name: Smoke Test
        working-directory: ./dev/jetbrains-test
        env:
          GATEWAY_PLUGIN_PATH: ../../components/ide/jetbrains/gateway-plugin/build/distributions/gitpod-gateway-test.zip
        run: |
          export GATEWAY_LINK=$(jq -r '.inputs.secret_gateway_link' $GITHUB_EVENT_PATH)
          gradle :test
          cp -r ./video/ ./build/reports
      - name: Move video
        if: always()
        run: |
          cp -r dev/jetbrains-test/video dev/jetbrains-test/build/reports
      - name: Save report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: video
          path: |
            dev/jetbrains-test/build/reports